spring.application.name=bms-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bms-Db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
